// All shared SVG <defs> for the hull: layered gradients (curved lit steel + anti-fouling
// paint + ambient-occlusion bands), a curved-metal micro-specular lighting filter, the
// bundled grime/grain/streak texture patterns, and the hull clip path. Kept here so the
// composition in Hull.tsx / HullPlating.tsx stays readable.
import { color } from '../../theme'
import { HULL, HULL_PATH } from './hullGeometry'

export default function HullDefs() {
  return (
    <defs>
      {/* topside steel: dark under the deck edge → mid steel → bright specular band just
          above the waterline → settling back to steel (sells a curved, lit plate) */}
      <linearGradient id="steelGradient" gradientUnits="userSpaceOnUse" x1="0" y1={HULL.deckY} x2="0" y2={HULL.keelY}>
        <stop offset="0%" stopColor={color.hullShadow} />
        <stop offset="10%" stopColor={color.hullSteel} />
        <stop offset="42%" stopColor={color.hullSteelLight} />
        <stop offset="55%" stopColor={color.hullSteelLight} />
        <stop offset="62%" stopColor={color.hullSteel} />
        <stop offset="100%" stopColor={color.hullShadow} />
      </linearGradient>

      {/* anti-fouling paint: brighter oxblood near the waterline, darkening toward the keel */}
      <linearGradient id="paintGradient" gradientUnits="userSpaceOnUse" x1="0" y1={HULL.waterlineY} x2="0" y2={HULL.keelY}>
        <stop offset="0%" stopColor={color.hullPaintBelow} />
        <stop offset="20%" stopColor={color.hullPaintBelow} />
        <stop offset="100%" stopColor={color.hullShadow} />
      </linearGradient>

      {/* ambient-occlusion shadow cast by the deck overhang along the top of the hull */}
      <linearGradient id="deckShadow" gradientUnits="userSpaceOnUse" x1="0" y1={HULL.deckY} x2="0" y2={HULL.deckY + 30}>
        <stop offset="0%" stopColor="#000" stopOpacity={0.55} />
        <stop offset="100%" stopColor="#000" stopOpacity={0} />
      </linearGradient>

      {/* soft length-wise light falloff: brightest amidships, darker toward bow & stern */}
      <linearGradient id="lengthFalloff" gradientUnits="userSpaceOnUse" x1={HULL.sternX} y1="0" x2={HULL.bowX} y2="0">
        <stop offset="0%" stopColor="#000" stopOpacity={0.32} />
        <stop offset="30%" stopColor="#000" stopOpacity={0} />
        <stop offset="70%" stopColor="#000" stopOpacity={0} />
        <stop offset="100%" stopColor="#000" stopOpacity={0.32} />
      </linearGradient>

      {/* rust bloom for stains bleeding from fittings */}
      <radialGradient id="rustBloom">
        <stop offset="0%" stopColor={color.signalRust} stopOpacity={0.55} />
        <stop offset="55%" stopColor={color.signalRustDim} stopOpacity={0.35} />
        <stop offset="100%" stopColor={color.signalRustDim} stopOpacity={0} />
      </radialGradient>

      {/* curved-metal micro-specular: turbulence relief lit by a high, raking light →
          dappled glints/relief that read as brushed, slightly wet steel */}
      <filter id="metalSpecular" x="0%" y="0%" width="100%" height="100%">
        <feTurbulence type="fractalNoise" baseFrequency="0.012 0.16" numOctaves={3} seed={8} result="noise" />
        <feSpecularLighting
          in="noise"
          surfaceScale={1.6}
          specularConstant={0.7}
          specularExponent={16}
          lightingColor={color.hullSteelLight}
          result="spec"
        >
          <feDistantLight azimuth={245} elevation={58} />
        </feSpecularLighting>
        <feComponentTransfer in="spec" result="specSoft">
          <feFuncA type="linear" slope={0.5} />
        </feComponentTransfer>
        <feComposite in="specSoft" in2="SourceGraphic" operator="in" />
      </filter>

      {/* bundled texture patterns (generated by scripts/gen-textures.mjs) */}
      <pattern id="grimePattern" patternUnits="userSpaceOnUse" width={620} height={300} patternTransform="rotate(2)">
        <image href="/textures/grime.png" width={620} height={300} preserveAspectRatio="none" />
      </pattern>
      <pattern id="grainPattern" patternUnits="userSpaceOnUse" width={260} height={150}>
        <image href="/textures/grain.png" width={260} height={150} preserveAspectRatio="none" />
      </pattern>
      <pattern id="streaksPattern" patternUnits="userSpaceOnUse" width={520} height={220}>
        <image href="/textures/streaks.png" width={520} height={220} preserveAspectRatio="none" />
      </pattern>

      <clipPath id="hullClip">
        <path d={HULL_PATH} />
      </clipPath>
    </defs>
  )
}
